[RPC] Fix Python SyntaxError in generated sai_adapter.py for sai_object_type_t
When generating sai_adapter.py using gensairpc.pl, attribute
SAI_COUNTER_ATTR_OBJECT_TYPE has the type 'sai_object_type_t'. Because
sai_object_type_t is not in $all_enums and not directly mapped in
sai_attribute_value_t thrift types, get_attr_type() returned undef.

This caused the template to generate invalid Python syntax:
    attribute_value = sai_thrift_attribute_value_t(=object_type)
instead of:
    attribute_value = sai_thrift_attribute_value_t(s32=object_type)

As a result, importing sai_thrift.sai_adapter on the PTF test controller
failed with:
    SyntaxError: invalid syntax

Add a special case in get_attr_type() to return 's32' when the attribute
type is 'sai_object_type_t'.

Signed-off-by: weipandeng <weipandeng@asterfusion.com>